### ISSUE TITLE
Excessive curl requests to validate the token

### ISSUE THREAD

**Issue by mudrd8mz** [go1com/moodle-mod_goone#12]
As noticed by @marinaglancy the module is triggering cURL calls via the `goone_tokentest()` too frequently. The call is performed - often even multiple times per request! - on every settings.php inclusion. Which makes it run all the time as the admin browses the admin tree, for example.

That seems wrong. Should not the token be validated in better defined situations / events only? Should not there be a cache with long enough TTL to avoid so frequent unnecessary calls?

**Comment by leegold** [comment]
Status: No further work
Effort: N/A
