### ISSUE TITLE
Fix code checker errors and warnings

### ISSUE THREAD

**Issue by cameorn1730** [go1com/moodle-mod_goone#13]
Running the latest commit (04d34f18) against the [Moodle code checker](https://github.com/moodlehq/moodle-local_codechecker) there are 34 errors and 35 warnings.

The MoodleCloud team considers this a blocker for integration with our service.

**Comment by fouad-ecreators** [comment]
Code checker issues resolved.
Only existing ones remain with a third party library which I don't believe needs to be rectified, please let me know if otherwise.

**Comment by cameorn1730** [comment]
Please add it to the plugin's thirdpartylibs.xml so it will be excluded from the code checker.

**Comment by leegold** [comment]
Blocker/trivial

**Comment by fouad-ecreators** [comment]
Correct Path added to thirdpartylibs.xml
