### ISSUE TITLE
Unit tests do not have sufficient coverage

### ISSUE THREAD

**Issue by cameorn1730** [go1com/moodle-mod_goone#14]
```
Code Coverage Report:
  2020-05-19 15:07:22

 Summary:
  Classes:  0.00% (0/1)
  Methods:  0.00% (0/6)
  Lines:    2.72% (11/404)
```

2.7% coverage is not sufficient to have any confidence that these tests are actually testing the plugin's functionality.

We expect lib.php and externallib.php to be sufficiently covered. Please see other parts of moodle for examples of how to do this.

**Comment by leegold** [comment]
Typical target coverage here is 25-33% for certified integrations.

Blocker as per past issue #11

**Comment by fouad-ecreators** [comment]
@cameorn1730 would it be possible to let me know which core plugin(s) follows the latest guidelines on the unit test so I don't accidentally read off an older one?
Also is there a way I can generate the coverage report myself?

Thanks

**Comment by cameorn1730** [comment]
You could check forum or assign. Both are actively maintained and should be a decent example.

For the coverage report, you need to modify phpunit.xml at the root of your moodle install. In the `<testsuites>` section, add:

`        <testsuite name="mod_goone_testsuite">
            <directory suffix="_test.php">mod/goone/tests</directory>
        </testsuite>`

Then at the bottom of the file, change the `<filter>` section (as in, remove what is currently there and replace it with this):

```
    <filter>
        <whitelist>
            <directory suffix=".php">mod/goone/externallib.php</directory>
            <directory suffix=".php">mod/goone/lib.php</directory>
            <exclude>
                <directory suffix=".php">lib/filestorage/tests</directory>
            </exclude>
        </whitelist>
    </filter>
```

Then from the root of your moodle install you can run: `vendor/bin/phpunit --testsuite mod_goone_testsuite --coverage-text`, or you can get a cooler HTML report with `vendor/bin/phpunit --testsuite mod_goone_testsuite --coverage-html ~/coverage_goone` which will put the report in a folder called "coverage_goone" in your home directory.

**Comment by fouad-ecreators** [comment]
Additional Unit tests added.
I've skipped integration tests for now and seperated some functions to be tested without requiring integrations.

**Comment by cameorn1730** [comment]
```
Code Coverage Report:
  2020-09-17 14:19:09

 Summary:
  Classes:  0.00% (0/1)
  Methods:  0.00% (0/6)
  Lines:   18.93% (78/412)
```

The new tests are an improvement. But still do not sufficiently cover lib.php

Digging deeper, lib.php is only ~20% covered. There are many functions that do not have tests covering them at all, and of the functions that do, there are many that could easily be covered better. For example, the "goone_supports" test only tests the default case (which is a quarter of the possible cases).

Please see my comment from May 21 on how to generate coverage reports. Ideally I'd like to see 50% coverage of lib.php - however >25% is still acceptable (as per Lee's comment on May 20) as long as testable functions are being properly tested (e.g., the goone_supports function).

Please feel free to reach out on this issue if you need any guidance.

Cheers,

Cam

**Comment by fouad-ecreators** [comment]
Hi Cameron,
Thanks for the feedback, I wasn't sure about testing the core'ish' functions like _supports and _update_instance, I'll make some changes and add more tests shortly.

**Comment by cameorn1730** [comment]
Hi Fouad,

This is definitely an improvement, cheers. However, my concerns [here](https://github.com/go1com/moodle-mod_goone/issues/14#issuecomment-693978732) have not been addressed. The goone_supports function is still not properly tested, for example. Additionaly, goone_signup URL is an easy function to unit test (and should therefore be covered).

Really, any function that does not perform a cURL request should have at least some coverage.

Feel free to reach out here if you need guidance.

Cheers,

Cam

**Comment by fouad-ecreators** [comment]
Hi Cam,
Thanks for looking at it again, with the goone_supports function are you looking for tests related to those features such as performing the backup/restore or actually testing that specific function?

**Comment by cameorn1730** [comment]
![image](https://user-images.githubusercontent.com/46586436/95552254-f899a100-0a3e-11eb-92af-b09b9ac1bf0d.png)

Only the base case is tested here. It would be trivial to test the other cases of the switch statement.

**Comment by fouad-ecreators** [comment]
Ah I see, my bad for not using the html coverage checker... and never specifically targetted that function.
I've just pushed some more tests, please let me know if it's on track now.
Thanks again for all the help.

**Comment by cameorn1730** [comment]
Hi Fouad,

My apologies for taking so long to reply to this.

I tried to run the unit tests with your latest commit, but they fail with: 

```
1) mod_goone_lib_testcase::test_goone_signup_url
Failed asserting that false is true
```

In lib_test line 156. Can you please ensure the testsuite passes?

Cheers,

Cam

**Comment by fouad-ecreators** [comment]
Hi Cam,
No worries at all.
Turns out I went a bit overboard with the code checker against line length and didn't split a string properly (and didnt recheck this specific test in my haste).
I've just pushed a very small fix to resolve that test case.

**Comment by cameorn1730** [comment]
Thanks Fouad,

I'm now seeing:

```
PHP Parse error:  syntax error, unexpected '}', expecting end of file in /home/cameron/.moodles/stable_master/moodle/mod/goone/tests/lib_test.php on line 161
```

Can you please ensure the testsuite passes before updating the issue again.

Cheers,

Cam

**Comment by fouad-ecreators** [comment]
Sorry Cam, It's been one of those days.
Fixed it now, pulled the code fresh and tests are OK

**Comment by cameorn1730** [comment]
Thanks Fouad,

Confirmed tests are passing, and I'm happy with the amount of coverage here. @leegold I'll close this then I think it's over to you for next steps.

Cheers!
