### ISSUE TITLE
Invalid name of the upgrade function

### ISSUE THREAD

**Issue by mudrd8mz** [go1com/moodle-mod_goone#2]
It seems the current upgrade code has been generated by an older version of the plugins skeleton generator that contained a bug https://github.com/mudrd8mz/moodle-tool_pluginskel/issues/90

As a result, the db/upgrade.php defines a function `xmldb_mod_goone_upgrade()` which should however be named `xmldb_goone_upgrade()`. The current code would fail with

```
Fatal error: Call to undefined function xmldb_goone_upgrade() in .../lib/upgradelib.php on line 726
```

**Comment by fouad-ecreators** [comment]
Thanks @mudrd8mz, resolved this by renaming the function.
